apiVersion: thinkube.io/v1
kind: ThinkubeDeployment
metadata:
  name: "{{ project_name }}"
  description: "{{ project_description }}"

spec:
  # Deployment mode - how containers are deployed
  deployment_mode: separate_pods  # Each container gets its own deployment
  
  # Container definitions
  containers:
    - name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - port: 8000
          name: http
      environment:
        - name: API_PREFIX
          value: "{{ api_prefix }}"
        - name: ENABLE_CORS
          value: "{{ enable_cors | string }}"
        {% if auth_provider != "none" %}
        - name: AUTH_PROVIDER
          value: "{{ auth_provider }}"
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: url
        {% endif %}
        {% if use_postgresql %}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "{{ project_name }}-db-credentials"
              key: url
        {% endif %}
      {% if use_postgresql %}
      dependencies:
        - postgresql
      {% endif %}
      healthcheck:
        path: "{{ api_prefix }}/health"
        port: 8000
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"

    - name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - name: VUE_APP_API_URL
            value: "https://{{ project_name }}.{{ domain_name }}{{ api_prefix }}"
          - name: VUE_APP_AUTH_PROVIDER
            value: "{{ auth_provider }}"
      ports:
        - port: 80
          name: http
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"

  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    rules:
      - host: "{{ project_name }}.{{ domain_name }}"
        paths:
          - path: "{{ api_prefix }}"
            service: backend
            port: 8000
          - path: /
            service: frontend
            port: 80
    tls:
      enabled: true
      # Certificate will be copied from thinkube wildcard cert

  # Optional features
  features:
    {% if use_postgresql %}
    postgresql:
      enabled: true
      size: "10Gi"
      version: "15"
    {% endif %}
    
    {% if enable_file_uploads %}
    storage:
      enabled: true
      size: "20Gi"
      mountPath: "/app/uploads"
      containers: ["backend"]
    {% endif %}
    
    {% if enable_websockets %}
    websockets:
      enabled: true
      container: backend
      path: "/ws"
    {% endif %}
    
    monitoring:
      enabled: true
      endpoints: ["{{ api_prefix }}/metrics"]
    
    backup:
      enabled: "{{ use_postgresql }}"
      schedule: "0 2 * * *"
      retention: "7d"

# 🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>