apiVersion: thinkube.io/v1
kind: ThinkubeDeployment

spec:
  # Container definitions
  containers:
    - name: backend
      build: ./backend
      port: 8000
      size: medium
      health: /health
      test:
        enabled: true
        image: "python-base:3.11-slim"
      
    - name: frontend
      build: ./frontend
      port: 80
      size: small
      health: /health
      test:
        enabled: true
        image: "node-base:18-alpine"

  # Routing configuration
  routes:
    - path: /api
      to: backend
    - path: /
      to: frontend

  # Services this application needs
  services:
    - database     # PostgreSQL for data persistence
    - cache        # For session storage and caching