apiVersion: thinkube.io/v1
kind: ThinkubeDeployment
metadata:
  name: "{{ project_name }}"
  description: "{{ project_description }}"

spec:
  # Container definitions
  containers:
    - name: backend
      build: ./backend
      port: 8000
      size: medium
      health: /api/v1/health
      
    - name: frontend
      build: ./frontend
      port: 80
      size: small

  # Routing configuration
  routes:
    - path: /api
      to: backend
    - path: /
      to: frontend

  # Services this application needs
  services:
    - database     # PostgreSQL for data persistence
    - cache        # For session storage and caching